@startuml
'https://plantuml.com/sequence-diagram

autonumber


actor "TrafficManager" as TM
participant ":System" as S
activate TM

TM -> S:  wants to know wich ships will be available on Monday next week and their location.

activate S

S --> TM: shows the information that was requested
deactivate S
deactivate TM
@enduml