@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "TrafficManager" as TM

participant ":US306UI" as SAUI
participant ":US306Controller" as SAC
participant ":US306" as US
participant ":WriteToFile" as WT



activate TM

TM -> SAUI:  wants to know the occupancy rate of all warehouses and the containers to leave in the next 30 days .

activate SAUI
SAUI -> SAC: createUS306
activate SAC

SAC -> US: create
activate US


US -> US:initialize
US -> WT: WriteTxt(info)
activate WT
deactivate WT


deactivate SAC
SAUI --> TM: shows the information.

deactivate SAUI
deactivate TM
@enduml