@startuml
'https://plantuml.com/sequence-diagram

autonumber


actor "Port Manager" as TM
participant ":System" as S
activate TM

TM -> S:  wants to generate, a week in advance, the loading\n and unloading map of manifests.

activate S

S --> TM: shows requested information
deactivate S
deactivate TM
@enduml