@startuml
'https://plantuml.com/class-diagram




class ContainerStore{
-containers
+calculateEnergySpecificRestrictions()
}



class US412Controller{
-company
-containerStore
+calculateEnergySpecificRestrictions()
}



class WriteTxt{
+writetxt()
}



US412Controller..>ContainerStore

US412Controller ..> WriteTxt


@enduml
