@startuml
'https://plantuml.com/sequence-diagram

autonumber


actor "Ship Chief Electrical Engineer" as TM
participant ":System" as S
activate TM

TM -> S:  wants to know how much energy to supply for a container

activate S

S --> TM: shows requested information
deactivate S
deactivate TM
@enduml