@startuml
'https://plantuml.com/sequence-diagram

autonumber


actor "Ship Chief Electrical Engineer" as TM
participant ":System" as S
activate TM

TM -> S:  wants to know the total energy needed to supply all containers \n keeping in mind the sides exposed to the sun

activate S

S --> TM: shows requested information
deactivate S
deactivate TM
@enduml