@startuml
autonumber

actor "Traffic Manager" as TM
participant ":System" as S

activate TM

TM-> S: wants to search the closest port to a ship.
activate S
S --> TM:  asks for Call Sign.
deactivate S
TM-> S: inserts the requested data.
activate S
S --> TM: shows the information.
deactivate S

deactivate TM
@enduml