@startuml
autonumber

actor "Traffic Manager" as TM
participant ":criticalPortUI" as IUI
participant ":criticalPortController" as IC
participant ":Company" as COMP
participant ":WriteTxt" as wrt


participant "graph\n:MatrixGraph" as graph



activate TM

TM-> IUI: asks to know wish to know which ports are more critical

activate IUI
IUI ->IC: criticalPort()
activate IC

IC -> COMP: getGraph()
activate COMP
deactivate COMP

IC -> graph : dijkstraNotContinent()
activate graph
deactivate graph

IC -> IC : calculateMostCritical()
activate IC
deactivate IC


IC -> wrt : writeToFile()
activate wrt
deactivate wrt


deactivate IC
IUI--> TM: shows the information
deactivate IUI
deactivate TM
@enduml