@startuml
'https://plantuml.com/sequence-diagram

autonumber


actor "PortManager" as PM
participant ":System" as S
activate PM

PM -> S:  wants to send a cargo manifest destined to a warehouse.

activate S

S --> PM: shows warning because warehouse is full
deactivate S
deactivate PM
@enduml