@startuml
'https://plantuml.com/sequence-diagram

autonumber


actor "TrafficManager" as TM
participant ":System" as S
activate TM

TM -> S:   wants to have access to audit trails for a given container of a given cargo manifest.

activate S

S --> TM: shows the information that was requested
deactivate S
deactivate TM
@enduml