@startuml
'https://plantuml.com/sequence-diagram

autonumber


actor "Ship Captain" as TM
participant ":System" as S
activate TM

TM -> S:  wants to know the center of mass for a vessel

activate S

S --> TM: shows requested information
deactivate S
deactivate TM
@enduml