@startuml
'https://plantuml.com/sequence-diagram

autonumber


actor "Fleet Manager" as TM
participant ":System" as S
activate TM

TM -> S:  wants to know the number of days each ship has been idle\n since the beginning of the current year.

activate S

S --> TM: shows requested information
deactivate S
deactivate TM
@enduml