@startuml

autonumber

actor "PortStaff" as PS
participant ":System" as S
activate PS

PS -> S: Wants to fill a statically reserved matrix in memory with each container's ID \n in its respective place, for a given a Cargo Manifest.

activate S

S --> PS: Shows the information that was requested.
deactivate S
deactivate PS

@enduml